### ISSUE TITLE
"Internal Error"

### ISSUE THREAD

**Issue by thekerp** [JurisProject/juris-builder#14]
"The files are here https://github.com/burrrata/interview-boilerplate so if you guys can get it working that would be awesome, but atm it's giving me the internal error again"

You can replicate the error by going to: https://builder.getjuris.com/run?i=https://raw.githubusercontent.com/burrrata/interview-boilerplate/master/interview.json&o=https://raw.githubusercontent.com/burrrata/interview-boilerplate/master/output.md

**Comment by yeqbfgxjiq** [comment]
Note: the error does not occur with smaller `output.md` template files. It's only with the large file that's currently in the repo.

**Comment by yeqbfgxjiq** [comment]
Removed 95% of the text and it worked fine, then added a few more pages (10%) of the text and it produced the same error again

**Comment by konstantinbrazhnik** [comment]
@burrrata I found a typo in your template that is probably breaking even my initial version.  You have a variable `{{DAO-ADDRESS}}` that is at least once referred to as `{{DAO ADDRESS}}`.

This typo causes the handlebars parser to look for a function called `DAO`, or as they call it, a helper. We'll definitely need to incorporate some kind of template checking/linting functionality in the future.

I'm refactoring the PDF generating function right now, but I believe this will fix it already.
